name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/*' # Triggers only for branches starting with "release/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment for building the Flutter integration
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the Node.js version your project needs

      # Step 3: Install dependencies in the Next.js app folder
      - name: Install dependencies for Next.js app
        run: npm install

      # Step 4: Build the Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 5: Deploy to Firebase Hosting
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
